### ISSUE TITLE
Implement the THIR unsafety checker

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/project-thir-unsafeck#7]
### Unsafe operations

- [x] CallToUnsafeFunction (rust-lang/rust#83129)
- [x] UseOfInlineAssembly (rust-lang/rust#85259)
- [x] InitializingTypeWith (rust-lang/rust#85381)
- [x] CastOfPointerToInt (rust-lang/rust#85381)
- [x] ~~BorrowOfPackedField~~ (removed -- see rust-lang/rust#82525)
- [x] UseOfMutableStatic (rust-lang/rust#85419)
- [x] UseOfExternStatic (rust-lang/rust#85419)
- [x] DerefOfRawPointer (rust-lang/rust#85306)
- [x] AssignToDroppingUnionField (rust-lang/rust#87403)
- [x] AccessToUnionField (rust-lang/rust#85263)
- [x] MutationOfLayoutConstrainedField (rust-lang/rust#86665)
- [x] BorrowOfLayoutConstrainedField (rust-lang/rust#86665)
- [x] CallToFunctionWith (rust-lang/rust#85306)

**Comment by LeSeulArtichaut** [comment]
@Smittyvb thanks for your help on this! If you plan on working on more unsafe operations, it would be great if you posted a comment here saying that you're doing it so we don't risk duplicate work. Or, if you intend to work regularly on this, you can ask to join the project group so you can edit the comment above directly.

**Comment by syvb** [comment]
@LeSeulArtichaut It appears that all of the unsafe operations have been implemented, I think this should be closed.
